# Generated by Django 5.0.7 on 2024-08-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0004_alter_label_name'),
        ('tasks', '0005_alter_task_options_alter_task_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(to='labels.label', verbose_name='Метки'),
        ),
    ]
