name: build

on:
  - push
  - pull_request

env:
  USE_LOCAL_DB: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
            python-version: 3.12

      - name: Install dependencies
        run: |
          pip install poetry
          make install install build

      - name: Run linter
        run: |
          make lint

      - name: Run tests
        run: |
          make test
